# Copyright 2017-2022 Peter Williams <peter@newton.cx> and collaborators
# Licensed under the MIT License.

[package]
name = "rubbl_core"
version = "0.0.0-dev.0"
authors = ["Peter Williams <peter@newton.cx>"]
license = "MIT"
edition = "2018"
homepage = "https://github.com/pkgw/rubbl"
repository = "https://github.com/pkgw/rubbl"
description = """
Core types and traits for Rubbl, a Rust package for astrophysics.
"""

[dependencies]
anyhow = { version = "1.0.0", features = ["backtrace"] }
byteorder = "1.4.0"
clap = { version = "4.0.26", features = ["cargo"] }
ndarray = "0.15.0"
num-complex = "0.4.0"
approx = { version = "0.5.0", features = ["num-complex"] }
termcolor = "1.1.0"
thiserror = "1.0.7"
