# Copyright 2017-2020 Peter Williams <peter@newton.cx> and collaborators
# Licensed under the MIT License.

[package]
name = "rubbl_casatables"
version = "0.0.0-dev.0"
authors = ["Peter Williams <peter@newton.cx>"]
license = "MIT"
edition = "2018"
homepage = "https://github.com/pkgw/rubbl"
repository = "https://github.com/pkgw/rubbl"
description = """
Interfacing to the CASA table format within the Rubbl framework.
"""

[package.metadata.internal_dep_versions]
rubbl_casatables_impl = "1d861e38cc1a40a6f0c984a58ae3dee54c27d127"
rubbl_core = "manual:^0.1.2"

[dependencies]
byteorder = "^1.3"
clap = "^2.33"
failure = "^0.1"
failure_derive = "^0.1"
itertools = "^0.9"
ndarray = "^0.14"
nom = "^6.0"
num-traits = "^0.2"
pbr = "^1.0"
rubbl_casatables_impl = { version ="0.0.0-dev.0", path = "../casatables_impl" }
rubbl_core = { version ="0.0.0-dev.0", path = "../core" }

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
