# Copyright 2017-2022 Peter Williams <peter@newton.cx> and collaborators
# Licensed under the MIT License.

[package]
name = "rubbl_casatables"
version = "0.0.0-dev.0"
authors = ["Peter Williams <peter@newton.cx>"]
license = "MIT"
edition = "2018"
homepage = "https://github.com/pkgw/rubbl"
repository = "https://github.com/pkgw/rubbl"
description = """
Interfacing to the CASA table format within the Rubbl framework.
"""

[package.metadata.internal_dep_versions]
rubbl_casatables_impl = "thiscommit:2021-11-04:9Lgzrtq"
rubbl_core = "thiscommit:2020-12-15:EiT8sa0a"

[dependencies]
ndarray = "0.15.0"
rubbl_casatables_impl = { version ="0.0.0-dev.0", path = "../casatables_impl" }
rubbl_core = { version ="0.0.0-dev.0", path = "../core" }
thiserror = "1.0.57"

[build-dependencies]
cc = { version = "1.0.90", features = ["parallel"] }

[dev-dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.2", features = ["cargo"] }
rubbl_core = { version ="0.0.0-dev.0", path = "../core", features = ["notifications"] }
tempfile = "3.10.1"
criterion = "0.3.*"
glob = "0.3"
flate2 = "1.0.20"
itertools = "0.10"
lazy_static = "1.4.0"
tar = "0.4.37"


[[bench]]
name = "bench"
# don't use path here, it breaks things.
harness = false
