# Generic setup in the deployment stage. We download all artifacts, install
# Cranko, and recover the `release` commit. We assume that we are running on
# Linux.

parameters:
- name: setupGit
  type: boolean
  default: false

steps:
- download: current

- checkout: self

- bash: |
    git switch -c release
    git pull --ff-only $(Pipeline.Workspace)/git-release/release.bundle
  displayName: Restore release commit

- bash: |
    set -euo pipefail
    d="$(mktemp -d /tmp/cranko.XXXXXX)"
    cd "$d"
    curl --proto '=https' --tlsv1.2 -sSf https://pkgw.github.io/cranko/fetch-latest.sh | sh
    echo "##vso[task.prependpath]$d"
  displayName: Install latest Cranko

- ${{ if parameters.setupGit }}:
  - bash: cranko github install-credential-helper
    displayName: Set up Git pushes
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
